atosite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
import autocomplete_light
from registration.backends.default.views import RegistrationView
from registration.forms import RegistrationFormUniqueEmail

autocomplete_light.autodiscover()

from care.views import UploadPictureView

class RegistrationViewUniqueEmail(RegistrationView):
    form_class = RegistrationFormUniqueEmail

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'atosite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^care/', include('care.urls', namespace="care")),
    url(r'^', include('ato.urls', namespace="ato")),
    url(r'^api/', include('api.urls', namespace="api")),
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^accounts/register/$', RegistrationViewUniqueEmail.as_view(), name='registration_register'),
    (r'^accounts/', include('registration.backends.default.urls')),
	
	(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^reset/', include('password_reset.urls')),
)

handler404 = 'care.views.custom_404'
handler403 = 'care.views.custom_404'
handler400 = 'care.views.custom_404'
handler500 = 'care.views.custom_404'

care/urls.py
from django.conf.urls import patterns, url
from django.contrib import auth

from care import views

urlpatterns = patterns('',
    url(r'^$', views.DetailView, name='detail'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'care/login.html', 'extra_context': {'next':'/care/detail'}}, name='login'),
    url(r'^logged/', views.logged, name='logged'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^detail/', views.DetailView, name='detail'),
    url(r'^loggedout/', views.loggedout, name='loggedout'),
    url(r'^myinfo/', views.InfoView, name='myinfo'),
    #Temp for debug
    url(r'^addupload/(?P<picture_id>\d+)/$', views.AddUploadView, name='addupload'),
    url(r'^addlike/(?P<picture_id>\d+)/$', views.AddLikeView, name='addlike'),
    url(r'^like/(?P<picture_id>\d+)/$', views.AddLikePhotographerView, name='like'),
    
    #end Temp for debug
    url(r'^upload/', views.UploadView, name='upload'),
    url(r'^addcategory/', views.AddCategoryView, name='addcat'),
    url(r'^addtag/', views.AddTagView, name='addtag'),
    url(r'^addlink/', views.AddLinkView, name='addlink'),
    url(r'^edit/(?P<picture_id>\d+)/$', views.EditView, name='edit'),
    url(r'^uploadpicture/$', views.UploadPictureView, name = 'jfu_upload' ),
    # You may optionally define a delete url as well
    url(r'^delete/(?P<pk>\d+)$', views.upload_delete, name = 'jfu_delete' ),
    url(r'^addthumb/', views.upload_thumb, name='add_thumb'),
    url(r'^adddescription/', views.upload_description, name='add_descr'),
    url(r'^getcategory/', views.GetCategoryView, name='get_cat'),
    url(r'^gettag/', views.GetTagView, name='get_tag'),
    url(r'^getpictures/', views.get_picture_list, name='get_pics'),
    url(r'^adduserphoto/$', views.upload_user_photo, name = 'upload_user_photo' ),
    url(r'^adduserthumb/$', views.upload_user_thumb, name = 'upload_user_thumb' ),
    
    url(r'^rotatephoto/$', views.rotate_photo, name = 'rotate_photo' ),

    url(r'^freeload/(?P<picture_id>\d+)/(?P<org_id>\d+)$', views.FreeLoadView, name='freeload'),
    url(r'^payform/(?P<picture_id>\d+)/(?P<org_id>\d+)$', views.PayLoadView, name='payform'),
    url(r'^donload/(?P<picture_id>\d+)/(?P<org_id>\d+)/(?P<ord_id>\d+)$', views.DonLoadView, name='donload'),

    url(r'^error/$', views.custom_404, name = 'error' ),
)

password_reset/urls.py
from django.conf.urls import url, patterns

from . import views


urlpatterns = patterns(
    '',
    url(r'^recover/(?P<signature>.+)/$', views.recover_done,
        name='password_reset_sent'),
    url(r'^recover/$', views.recover, name='password_reset_recover'),
    url(r'^reset/done/$', views.reset_done, name='password_reset_done'),
    url(r'^reset/(?P<token>[\w:-]+)/$', views.reset,
        name='password_reset_reset'),
)

urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
import autocomplete_light

autocomplete_light.autodiscover()

from care.views import UploadView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'atosite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^care/', include('care.urls', namespace="care")),
    url(r'^admin/', include(admin.site.urls)),
    (r'^accounts/', include('registration.backends.default.urls')),
	(r'^accounts/', include('django.contrib.auth.urls')),
	(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	url(r'^autocomplete/', include('autocomplete_light.urls')),
)

password_reset/forms.py
from django import forms
from django.core.validators import validate_email
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _

from .utils import get_user_model


class PasswordRecoveryForm(forms.Form):
    username_or_email = forms.CharField()

    def __init__(self, *args, **kwargs):
        self.case_sensitive = kwargs.pop('case_sensitive', True)
        search_fields = kwargs.pop('search_fields', ('username', 'email'))
        super(PasswordRecoveryForm, self).__init__(*args, **kwargs)

        message = ("No other fields than username and email are supported "
                   "by default")
        if len(search_fields) not in (1, 2):
            raise ValueError(message)
        for field in search_fields:
            if field not in ['username', 'email']:
                raise ValueError(message)

        labels = {
            'username': _('Username'),
            'email': _('Email'),
            'both': _('Username or Email'),
        }
        User = get_user_model()  # noqa
        if getattr(User, 'USERNAME_FIELD', 'username') == 'email':
            self.label_key = 'email'
        elif len(search_fields) == 1:
            self.label_key = search_fields[0]
        else:
            self.label_key = 'both'
        self.fields['username_or_email'].label = labels[self.label_key]

    def clean_username_or_email(self):
        username = self.cleaned_data['username_or_email']
        cleaner = getattr(self, 'get_user_by_%s' % self.label_key)
        self.cleaned_data['user'] = cleaner(username)
        return username

    def get_user_by_username(self, username):
        key = 'username__%sexact' % ('' if self.case_sensitive else 'i')
        User = get_user_model()
        try:
            user = User._default_manager.get(**{key: username})
        except User.DoesNotExist:
            raise forms.ValidationError(_("Sorry, this user doesn't exist."))
        return user

    def get_user_by_email(self, email):
        validate_email(email)
        key = 'email__%sexact' % ('' if self.case_sensitive else 'i')
        User = get_user_model()
        try:
            user = User._default_manager.get(**{key: email})
        except User.DoesNotExist:
            raise forms.ValidationError(_("Sorry, this user doesn't exist."))
        return user

    def get_user_by_both(self, username):
        key = '__%sexact'
        key = key % '' if self.case_sensitive else key % 'i'
        f = lambda field: Q(**{field + key: username})
        filters = f('username') | f('email')
        User = get_user_model()
        try:
            user = User._default_manager.get(filters)
        except User.DoesNotExist:
            raise forms.ValidationError(_("Sorry, this user doesn't exist."))
        except User.MultipleObjectsReturned:
            raise forms.ValidationError(_("Unable to find user."))
        return user


class PasswordResetForm(forms.Form):
    password1 = forms.CharField(
        label=_('New password'),
        widget=forms.PasswordInput,
    )
    password2 = forms.CharField(
        label=_('New password (confirm)'),
        widget=forms.PasswordInput,
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(PasswordResetForm, self).__init__(*args, **kwargs)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1', '')
        password2 = self.cleaned_data['password2']
        if not password1 == password2:
            raise forms.ValidationError(_("The two passwords didn't match."))
        return password2

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data['password1'])
        if commit:
            get_user_model()._default_manager.filter(pk=self.user.pk).update(
                password=self.user.password,
            )
        return self.user

password_reset/views.py
import datetime

from django.conf import settings
from django.contrib.sites.models import RequestSite
from django.core import signing
from django.core.mail import send_mail, EmailMultiAlternatives
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.http import Http404
from django.template import loader
from django.utils import timezone
from django.views import generic

from .forms import PasswordRecoveryForm, PasswordResetForm
from .utils import get_user_model, get_username
from .signals import user_recovers_password


class SaltMixin(object):
    salt = 'password_recovery'
    url_salt = 'password_recovery_url'


def loads_with_timestamp(value, salt):
    """Returns the unsigned value along with its timestamp, the time when it
    got dumped."""
    try:
        signing.loads(value, salt=salt, max_age=-1)
    except signing.SignatureExpired as e:
        age = float(str(e).split('Signature age ')[1].split(' >')[0])
        timestamp = timezone.now() - datetime.timedelta(seconds=age)
        return timestamp, signing.loads(value, salt=salt)


class RecoverDone(SaltMixin, generic.TemplateView):
    template_name = "password_reset/reset_sent.html"

    def get_context_data(self, **kwargs):
        ctx = super(RecoverDone, self).get_context_data(**kwargs)
        try:
            ctx['timestamp'], ctx['email'] = loads_with_timestamp(
                self.kwargs['signature'], salt=self.url_salt,
            )
        except signing.BadSignature:
            raise Http404
        return ctx
recover_done = RecoverDone.as_view()


class Recover(SaltMixin, generic.FormView):
    case_sensitive = True
    form_class = PasswordRecoveryForm
    template_name = 'password_reset/recovery_form.html'
    email_template_name = 'password_reset/recovery_email.txt'
    email_template_html_name = 'password_reset/recovery_email.html'
    email_subject_template_name = 'password_reset/recovery_email_subject.txt'
    search_fields = ['username', 'email']

    def get_success_url(self):
        return reverse('password_reset_sent', args=[self.mail_signature])

    def get_context_data(self, **kwargs):
        kwargs['url'] = self.request.get_full_path()
        return super(Recover, self).get_context_data(**kwargs)

    def get_form_kwargs(self):
        kwargs = super(Recover, self).get_form_kwargs()
        kwargs.update({
            'case_sensitive': self.case_sensitive,
            'search_fields': self.search_fields,
        })
        return kwargs

    def send_notification(self):
        context = {
            'site': RequestSite(self.request),
            'user': self.user,
            'username': get_username(self.user),
            'token': signing.dumps(self.user.pk, salt=self.salt),
            'secure': self.request.is_secure(),
        }
        body = loader.render_to_string(self.email_template_name,
                                       context).strip()
        subject = loader.render_to_string(self.email_subject_template_name,
                                          context).strip()
        email_send = EmailMultiAlternatives(subject, body, settings.DEFAULT_FROM_EMAIL,
                  [self.user.email])
        message_html = loader.render_to_string(self.email_template_html_name,
                                       context).strip()
        email_send.attach_alternative(message_html, 'text/html')
        email_send.send()


    def form_valid(self, form):
        self.user = form.cleaned_data['user']
        self.send_notification()
        if (
            len(self.search_fields) == 1 and
            self.search_fields[0] == 'username'
        ):
            # if we only search by username, don't disclose the user email
            # since it may now be public information.
            email = self.user.username
        else:
            email = self.user.email
        self.mail_signature = signing.dumps(email, salt=self.url_salt)
        return super(Recover, self).form_valid(form)
recover = Recover.as_view()


class Reset(SaltMixin, generic.FormView):
    form_class = PasswordResetForm
    token_expires = 3600 * 48  # Two days
    template_name = 'password_reset/reset.html'
    success_url = reverse_lazy('password_reset_done')

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        self.args = args
        self.kwargs = kwargs

        try:
            pk = signing.loads(kwargs['token'], max_age=self.token_expires,
                               salt=self.salt)
        except signing.BadSignature:
            return self.invalid()

        self.user = get_object_or_404(get_user_model(), pk=pk)
        return super(Reset, self).dispatch(request, *args, **kwargs)

    def invalid(self):
        return self.render_to_response(self.get_context_data(invalid=True))

    def get_form_kwargs(self):
        kwargs = super(Reset, self).get_form_kwargs()
        kwargs['user'] = self.user
        return kwargs

    def get_context_data(self, **kwargs):
        ctx = super(Reset, self).get_context_data(**kwargs)
        if 'invalid' not in ctx:
            ctx.update({
                'username': get_username(self.user),
                'token': self.kwargs['token'],
            })
        return ctx

    def form_valid(self, form):
        form.save()
        user_recovers_password.send(
            sender=get_user_model(),
            user=form.user,
            request=self.request
        )
        return redirect(self.get_success_url())
reset = Reset.as_view()


class ResetDone(generic.TemplateView):
    template_name = 'password_reset/recovery_done.html'


reset_done = ResetDone.as_view()

care/templates/password_reset/recovery_done.html
{% extends "care/base.html"  %}
{% load i18n %}

{% block title %}{% trans "New password set" %}{% endblock %}

{% block pagetitle %}{% trans "New password set" %}{% endblock %}


{% block content %}
<form class="form-signin text-center" >
	<p>{% trans "Your password has successfully been reset. You can use it right now on the " %}
		<a href="/care">{% trans "login page" %}</a>.</p>
</form>

<script language="javascript" type="text/javascript">
     <!--
     window.setTimeout('window.location="/care/login"; ',2800);
     // -->
 </script>
{% endblock %}

care/templates/password_reset/recovery_email.html
{% load i18n %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width"/>

    
    <style type="text/css">

    * {
  margin: 0;
  padding: 0;
  font-size: 100%;
  font-family: 'Avenir Next', "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
  line-height: 1.65; }

img {
  max-width: 100%;
  margin: 0 auto;
  display: block; }

body,
.body-wrap {
  width: 100% !important;
  height: 100%;
  background: #efefef;
  -webkit-font-smoothing: antialiased;
  -webkit-text-size-adjust: none; }

a {
  color: #5bc0de;
  text-decoration: none; }

.text-center {
  text-align: center; }

.text-right {
  text-align: right; }

.text-left {
  text-align: left; }

.button {
  display: inline-block;
  color: white;
  background: #5bc0de;
  border: solid #46b8da;
  border-width: 10px 20px 8px;
  font-weight: bold;
  border-radius: 4px; }

h1, h2, h3, h4, h5, h6 {
  margin-bottom: 20px;
  line-height: 1.25; }

h1 {
  font-size: 32px; }

h2 {
  font-size: 28px; }

h3 {
  font-size: 24px; }

h4 {
  font-size: 20px; }

h5 {
  font-size: 16px; }

p, ul, ol {
  font-size: 16px;
  font-weight: normal;
  margin-bottom: 20px; }

.container {
  display: block !important;
  clear: both !important;
  margin: 0 auto !important;
  max-width: 580px !important; }
  .container table {
    width: 100% !important;
    border-collapse: collapse; }
  .container .masthead {
    padding: 80px 0;
    background: #5bc0de;
    color: white; }
    .container .masthead h1 {
      margin: 0 auto !important;
      max-width: 90%; }
  .container .content {
    background: white;
    padding: 30px 35px; }
    .container .content.footer {
      background: none; }
      .container .content.footer p {
        margin-bottom: 0;
        color: #888;
        text-align: center;
        font-size: 14px; }
      .container .content.footer a {
        color: #888;
        text-decoration: none;
        font-weight: bold; }


    </style>
</head>
<body>
<table class="body-wrap" style="

display: table;
border-collapse: separate;
border-spacing: 2px;
border-color: gray;

white-space: normal;
line-height: normal;
font-weight: normal;
font-size: medium;
font-variant: normal;
font-style: normal;
color: -webkit-text;
text-align: start;

margin: 0;
padding: 0;
font-size: 100%;
font-family: 'Avenir Next', 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
line-height: 1.65;

width: 100% !important;
height: 100%;
background: #efefef;
-webkit-font-smoothing: antialiased;
-webkit-text-size-adjust: none;

">
    <tr>
        <td class="container" style="display: block !important;
clear: both !important;
margin: 0 auto !important;
max-width: 580px !important;">

            <!-- Message start -->
            <table style="width: 100%;">
                <tr>
                    <td align="center" class="masthead" style="padding: 80px 0;
background: #5bc0de;
color: white;">

                        <h1 style="line-height: 1.25;font-size: 32px;margin: 0 auto !important;
max-width: 90%;color: white;">pics.Care</h1>

                    </td>
                </tr>
                <tr>
                    <td class="content" style="background: white;
padding: 30px 35px;">

                        <h2 style="font-size: 28px;">{% blocktrans %}Dear {{ username }},{% endblocktrans %}</h2>

                                                <p style="font-size: 16px;
font-weight: normal;
margin-bottom: 20px;">{% blocktrans with domain=site.domain %}You -- or someone pretending to be you -- has requested a password reset on {{ domain }}.{% endblocktrans %}
</p>

                        <p style="font-size: 16px;
font-weight: normal;
margin-bottom: 20px;">{% trans "You can set your new password by following this link:" %}</p>

                        <table style="width: 100%;">
                            <tr>
                                <td align="center">
                                    <p style="font-size: 16px;
font-weight: normal;
margin-bottom: 20px;">
                                        <a style="color: #5bc0de;
text-decoration: none;

display: inline-block;
color: white;
background: #5bc0de;
border: solid #46b8da;
border-width: 10px 20px 8px;
font-weight: bold;
border-radius: 4px;" href="http{% if secure %}s{% endif %}://{{ site.domain }}{% url 'password_reset_reset' token %}" class="button">{% trans "Recover!" %}</a>
                                    </p>
                                </td>
                            </tr>
                        </table>

                        <p style="font-size: 16px;
font-weight: normal;
margin-bottom: 20px;">{% trans "Or just click " %} <a style="

color: #5bc0de;
text-decoration: none;

" href="http{% if secure %}s{% endif %}://{{ site.domain }}{% url 'password_reset_reset' token %}">{% trans "here" %}</a>.</p>

                        <p style="font-size: 16px;
font-weight: normal;
margin-bottom: 20px;">{% trans "If you don't want to reset your password, simply ignore this email and it will stay unchanged." %}</p>

                        <p style="font-size: 16px;
font-weight: normal;
margin-bottom: 20px;"><em>–{% trans "Thank you!" %} pics.Care</em></p>

                    </td>
                </tr>
            </table>

        </td>
    </tr>
    <tr>
        <td class="container" style="display: block !important;
clear: both !important;
margin: 0 auto !important;
max-width: 580px !important;">

            <!-- Message start -->
            <table  style="width: 100%;">
                <tr>
                    <td class="content footer" align="center" style="padding: 30px 35px;background: #efefef;">
                        <p style="margin-bottom: 0;
color: #888;
text-align: center;
font-size: 14px;"><a style="color: #888;
text-decoration: none;" href="http://{{ site }}">pics.Care</a></p>
                        <p style="margin-bottom: 0;
color: #888;
text-align: center;
font-size: 14px;"><a style="color: #888;
text-decoration: none;" href="mailto:pics.ato.care@gmail.com">pics.ato.care@gmail.com</a></p>
                    </td>
                </tr>
            </table>

        </td>
    </tr>
</table>
</body>
</html>

care/templates/password_reset/recovery_form.html
{% extends "care/base.html"  %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Password recovery" %}{% endblock %}

{% block pagetitle %}{% trans "Password recovery" %}{% endblock %}

{% block content %}

	
	<form method="post" action="{{ url }}" class="form-signin text-center" >
		{% csrf_token %}
		<h1 class="form-signin-heading">{% trans "Password recovery" %}</h1>
	
		<p>{% trans "Forgotten your password? Enter your e-mail address or username below, and we'll e-mail instructions for setting a new one." %}</p>

		{% if form.errors %}
			<div class="alert alert-danger  text-left">
	                    <span class="glyphicon glyphicon-remove"></span><strong> {% trans "Error!" %} {{form.errors}}</strong>
	                </div>
			{% endif %}

		<p>
			<input id="id_username_or_email" name="username_or_email" type="text" class="form-control" placeholder="Username" required="" autofocus=""></p>
		<p><input type="submit" value="{% trans "Recover my password" %}" class="btn btn-info "></p>
	</form>
{% endblock %}

care/templates/password_reset/reset.html
{% extends "care/base.html"  %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Password recovery" %}{% endblock %}

{% block pagetitle %}{% trans "Password recovery" %}{% endblock %}

{% block content %}

	{% if invalid %}{% url "password_reset_recover" as recovery_url %}
		<p>{% blocktrans %}Sorry, this password reset link is invalid. You can still <a href="{{ recovery_url }}">request a new one</a>.{% endblocktrans %}</p>
	{% else %}
	<form method="post" action="{% url 'password_reset_reset' token %}" class="form-signin text-center">
		{% csrf_token %}
		<h2 class="form-signin-heading">{% blocktrans %}Hi, <strong>{{ username }}</strong>.{% endblocktrans %}</h2>
	
		<h4>{% blocktrans %}Please choose your new password.{% endblocktrans %}</h4>
		<hr>
		{% if form.errors %}
			<div class="alert alert-danger text-left">
                <span class="glyphicon glyphicon-remove"></span><strong> {% trans "Error!" %} {{form.errors}}</strong>
            </div>
        {% endif %}
		<div class="row">
			<div class="col-md-12">

				<div class="form-group" style="width: 100%;">
					<label for="id_password1">{% trans "New password:" %}</label> 
					<div class="input-group" style="width: 100%;">
						<input id="id_password1" name="password1" type="password" class="form-control" required="" autofocus="">
					</div>

				</div>
				<div class="form-group" style="width: 100%;">
					<label for="id_password2">{% trans "New password (confirm):" %}</label> 
					<div class="input-group" style="width: 100%;">
						<input id="id_password2" name="password2" type="password" class="form-control" required="" autofocus="">
					</div>

				</div>
				</div>
		</div>

		<p><input type="submit" value="{% trans "Recover my password" %}" class="btn btn-info "></p>
	</form>
	{% endif %}
{% endblock %}

care/templates/password_reset/reset_sent.html
{% extends "care/base.html"  %}
{% load i18n %}

{% block title %}{% trans "Password recovery sent" %}{% endblock %}

{% block pagetitle %}{% trans "Password recovery sent" %}{% endblock %}


{% block content %}
<form class="form-signin text-center" >
	<p>{% blocktrans %}An email was sent to <strong>{{ email }}</strong>. Use the link in it to set a new password.{% endblocktrans %}</p>
</form>
{% endblock %}