ato/urls.py
from django.conf.urls import patterns, url
from django.contrib import auth

from ato import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView, name='index'),
    url(r'^ua/$', views.IndexUAView, name='index'),
    url(r'^en/$', views.IndexENView, name='index'),
    url(r'^ppen/$', views.PPEView, name='ppEnglish'),
    url(r'^ppua/$', views.PPUView, name='ppUkrainian'),
    url(r'^social/', views.SocialView, name='social'),
    url(r'^google8be9593cfc04aaac/', views.GoogleMerchView, name='GoogleMerch'),
    url(r'^google8be9593cfc04aaac.html', views.GoogleMerchView, name='GoogleMerch'),
)

atosite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
import autocomplete_light
from registration.backends.default.views import RegistrationView
from registration.forms import RegistrationFormUniqueEmail

autocomplete_light.autodiscover()

from care.views import UploadPictureView

class RegistrationViewUniqueEmail(RegistrationView):
    form_class = RegistrationFormUniqueEmail

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'atosite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^care/', include('care.urls', namespace="care")),
    url(r'^', include('ato.urls', namespace="ato")),
    url(r'^api/', include('api.urls', namespace="api")),
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^accounts/register/$', RegistrationViewUniqueEmail.as_view(), name='registration_register'),
    (r'^accounts/', include('registration.backends.default.urls')),
	
	(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^reset/', include('password_reset.urls')),
)

handler404 = 'care.views.custom_404'
handler403 = 'care.views.custom_404'
handler400 = 'care.views.custom_404'
handler500 = 'care.views.custom_404'

care/urls.py
from django.conf.urls import patterns, url
from django.contrib import auth

from care import views

urlpatterns = patterns('',
    url(r'^$', views.DetailView, name='detail'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'care/login.html', 'extra_context': {'next':'/care/detail'}}, name='login'),
    url(r'^logged/', views.logged, name='logged'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^detail/', views.DetailView, name='detail'),
    url(r'^loggedout/', views.loggedout, name='loggedout'),
    url(r'^myinfo/', views.InfoView, name='myinfo'),
    #Temp for debug
    url(r'^addupload/(?P<picture_id>\d+)/$', views.AddUploadView, name='addupload'),
    url(r'^addlike/(?P<picture_id>\d+)/$', views.AddLikeView, name='addlike'),
    url(r'^like/(?P<picture_id>\d+)/$', views.AddLikePhotographerView, name='like'),
    
    #end Temp for debug
    url(r'^upload/', views.UploadView, name='upload'),
    url(r'^addcategory/', views.AddCategoryView, name='addcat'),
    url(r'^addtag/', views.AddTagView, name='addtag'),
    url(r'^addlink/', views.AddLinkView, name='addlink'),
    url(r'^edit/(?P<picture_id>\d+)/$', views.EditView, name='edit'),
    url(r'^uploadpicture/$', views.UploadPictureView, name = 'jfu_upload' ),
    # You may optionally define a delete url as well
    url(r'^delete/(?P<pk>\d+)$', views.upload_delete, name = 'jfu_delete' ),
    url(r'^addthumb/', views.upload_thumb, name='add_thumb'),
    url(r'^adddescription/', views.upload_description, name='add_descr'),
    url(r'^getcategory/', views.GetCategoryView, name='get_cat'),
    url(r'^gettag/', views.GetTagView, name='get_tag'),
    url(r'^getpictures/', views.get_picture_list, name='get_pics'),
    url(r'^adduserphoto/$', views.upload_user_photo, name = 'upload_user_photo' ),
    url(r'^adduserthumb/$', views.upload_user_thumb, name = 'upload_user_thumb' ),
    
    url(r'^rotatephoto/$', views.rotate_photo, name = 'rotate_photo' ),

    url(r'^freeload/(?P<picture_id>\d+)/(?P<org_id>\d+)$', views.FreeLoadView, name='freeload'),
    url(r'^payform/(?P<picture_id>\d+)/(?P<org_id>\d+)$', views.PayLoadView, name='payform'),
    url(r'^donload/(?P<picture_id>\d+)/(?P<org_id>\d+)/(?P<ord_id>\d+)$', views.DonLoadView, name='donload'),

    url(r'^error/$', views.custom_404, name = 'error' ),
)

urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
import autocomplete_light

autocomplete_light.autodiscover()

from care.views import UploadView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'atosite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^care/', include('care.urls', namespace="care")),
    url(r'^admin/', include(admin.site.urls)),
    (r'^accounts/', include('registration.backends.default.urls')),
	(r'^accounts/', include('django.contrib.auth.urls')),
	(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	url(r'^autocomplete/', include('autocomplete_light.urls')),
)

care/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image, ImageDraw, ImageFont, ImageEnhance
import sys, time
import hashlib
from uuid import uuid4
import os
from django import forms
from multilingual_model.models import MultilingualModel, MultilingualTranslation
from django.utils.encoding import smart_unicode
from django.utils.translation import ugettext as _
from django.conf import settings
import helpers
from django.utils.deconstruct import deconstructible
from django.db.models.signals import pre_delete


class Tag(MultilingualModel):
	#tag_name = models.CharField(verbose_name=_(u"#tagname"), max_length=50)
	date_pub = models.DateTimeField(auto_now_add=True)
	approve_status = models.BooleanField(default=False)
	author = models.ForeignKey(User)
	def __str__(self):
		try:
			if self.name:
				return self.name.encode('utf-8')
			else:
				return _(u'Unnamed').encode('utf-8')
		except TagTranslation.DoesNotExist:
			return 'None'
	@classmethod
	def create(cls, author):
		tag_obj = cls(author=author)
		# do something with the picture
		return tag_obj


class TagTranslation(MultilingualTranslation):
	class Meta:
		unique_together = ('parent', 'language_code')

	parent = models.ForeignKey(Tag, related_name='translations')
	name = models.CharField(verbose_name=_(u"#tagname"), max_length=75)


class Category(MultilingualModel):
	def download_count(self):
		return self.download_set.filter().count()

	date_pub = models.DateTimeField(auto_now_add=True)
	approve_status = models.BooleanField(default=False)
	author = models.ForeignKey(User)

	def __str__(self):
		try:
			if self.name:
				return self.name.encode('utf-8')
			else:
				return _(u'Unnamed').encode('utf-8')
		except CategoryTranslation.DoesNotExist:
			return 'None'
	@classmethod
	def create(cls, author):
		cat_obj = cls(author=author)
		# do something with the picture
		return cat_obj


class CategoryTranslation(MultilingualTranslation):
	class Meta:
		unique_together = ('parent', 'language_code')

	parent = models.ForeignKey(Category, related_name='translations')
	name = models.CharField(verbose_name=_(u"Category name"), max_length=75)

@deconstructible
class PathAndRename(object):

	def __init__(self, sub_path):
		self.path = sub_path

	def __call__(self, instance, filename):
		now = str(int(time.time()))
		hashPath = hashlib.md5(now).hexdigest()
		path = 'gallery/'+hashPath[:2]+'/'+hashPath[2:4]+'/'+hashPath+'/'
		ext = filename.split('.')[-1]
		# get filename
		filename = '{}.{}'.format(uuid4().hex, ext)
		# return the whole path to the file
		return os.path.join(path, filename)

class Picture(MultilingualModel):

	"""
	four size sets:
		thumbnail (photo_big_thumb)
		bigthumbnail (photo_thumb)
		medium (photo_medium)
		original (photo_FULL_HD)
	"""

	path_and_rename = PathAndRename('gallerydef/')


	#picture_name = models.CharField(verbose_name=_(u"Picture name"), maxength=100)
	date_pub = models.DateTimeField(auto_now_add=True, auto_now=True)
	approve_status = models.BooleanField(default=False)
	complete_status = models.BooleanField(default=False)
	date_approve = models.DateTimeField(null=True)
	photo_origin = models.ImageField(verbose_name=_(u"original file upload"), upload_to=path_and_rename)
	photo_medium = models.CharField(max_length=255, blank=True)
	photo_big_thumb = models.CharField(max_length=255, blank=True, default='')
	photo_thumb = models.CharField(max_length=255, blank=True)
	category = models.ManyToManyField(Category, blank=True)
	tag = models.ManyToManyField(Tag, blank=True)
	author = models.ForeignKey(User)

	def download_count(self):
		return self.download_set.filter().count()

	def amount_count(self):
		aggregation = self.download_set.filter().aggregate(price=Sum('amount'))
		return float(aggregation.get('price', 0)) * settings.DONATED_LEFT if aggregation.get('price', 0) else 0

	def __str__(self):
		try:
			if self.name:
				return self.name.encode('utf-8')
			else:
				return _(u'Unnamed').encode('utf-8')
		except PictureTranslation.DoesNotExist:
			return 'None'

	def get_thumb(self):
		return "/media/%s" % self.photo_thumb

	def get_big_thumb(self):
		return "/media/%s" % self.photo_big_thumb

	def get_medium(self):
		return "/media/%s" % self.photo_medium

	def get_original(self):
		return "/media/%s" % self.photo_origin

	def __iter__(self):
		return self

	def admin_thumbnail(self):
		return u'<img src="/media/%s" />' % (self.photo_thumb)
	admin_thumbnail.short_description = _(u'Thumbnail')
	admin_thumbnail.allow_tags = True

	def admin_image(self):
		return u'<img src="/media/%s" />' % (self.photo_medium)
	admin_image.short_description = _(u'Image')
	admin_image.allow_tags = True

	@classmethod
	def create(cls, picture, user_added):
		image_obj = cls(photo_origin=picture, author=user_added)
		# do something with the picture
		return image_obj

	def save(self):
		sizes = {'big_thumbnail': {'height': 600, 'width': 600}, 'thumbnail': {'height': 240, 'width': 320}, 'medium': {'height': 480, 'width': 640}, 'fullHD': {'height': 1080, 'width': 1920},}

		super(Picture, self).save()
		if not self.photo_medium:
			photopath = str(self.photo_origin.path)  # this returns the full system path to the original file
			print photopath
			im = Image.open(photopath)  # open the image using PIL

			# pull a few variables out of that full path
			extension = photopath.rsplit('.', 1)[1]  # the file extension
			filename = photopath.rsplit('/', 1)[1].rsplit('.', 1)[0]  # the file name only (minus path or extension)
			fullpath = photopath.rsplit('/', 1)[0]  # the path only (minus the filename.extension)

			# use the file extension to determine if the image is valid before proceeding
			if extension.lower() not in ['jpg', 'jpeg', 'gif', 'png']:
				super(Picture, self).delete()
				sys.exit()

			now = str(int(time.time()))
			hashPath = hashlib.md5(now).hexdigest()
			filepath = 'gallery/'+hashPath[:2]+'/'+hashPath[2:4]+'/'+hashPath+'/'

			(width, height) = im.size

			if(width > height):
				# create fullHD image lands
				im.thumbnail((sizes['fullHD']['width'], sizes['fullHD']['height']), Image.ANTIALIAS)
			else:
				# create fullHD image port
				im.thumbnail((sizes['fullHD']['height'], sizes['fullHD']['width']), Image.ANTIALIAS)

			fullHD = filename + ".jpg"
			im.save(fullpath + '/' + fullHD)

			if(width > height):
				# create medium image lands
				im.thumbnail((sizes['medium']['width'], sizes['medium']['height']), Image.ANTIALIAS)
			else:
				# create medium image port
				im.thumbnail((sizes['medium']['height'], sizes['medium']['width']), Image.ANTIALIAS)
			#medname = filename + "_" + str(sizes['medium']['width']) + "x" + str(sizes['medium']['height']) + ".jpg"
			medname = uuid4().hex + ".jpg"
			im.save(fullpath + '/' + medname)

			self.photo_medium = filepath + medname

			# create thumbnail small (sqare - no need lands or port)
			im.thumbnail((sizes['thumbnail']['width'], sizes['thumbnail']['height']), Image.ANTIALIAS)
			#thumbname = filename + "_" + str(sizes['thumbnail']['width']) + "x" + str(sizes['thumbnail']['height']) + ".jpg"
			thumbname = uuid4().hex + ".jpg"
			im.save(fullpath + '/' + thumbname)
			#add_watermark(fullpath + '/' + thumbname, "ATO.care", fullpath + '/' + thumbname)
			self.photo_thumb = filepath + thumbname

			# create thumbnail small (sqare - no need lands or port)
			im.thumbnail((sizes['big_thumbnail']['width'], sizes['big_thumbnail']['height']), Image.ANTIALIAS)
			big_thumbname = uuid4().hex + ".jpg"
			im.save(fullpath + '/' + big_thumbname)
			self.photo_big_thumb = filepath + big_thumbname

			super(Picture, self).save()
			#add_watermark(fullpath + '/' + medname, "ATO.care", fullpath + '/' + medname)


def file_cleanup(sender, instance, *args, **kwargs):
	'''
		Deletes the file(s) associated with a model instance. The model
		is not saved after deletion of the file(s) since this is meant
		to be used with the pre_delete signal.
	'''

	try:
		print("Delete preview "+settings.MEDIA_ROOT + instance.photo_medium)
		os.remove(settings.MEDIA_ROOT + instance.photo_medium)
		print("Delete thumbnail "+settings.MEDIA_ROOT + instance.photo_thumb)
		os.remove(settings.MEDIA_ROOT + instance.photo_thumb)
		print("Delete big thumbnail "+settings.MEDIA_ROOT + instance.photo_big_thumb)
		os.remove(settings.MEDIA_ROOT + instance.photo_big_thumb)
	except:
		print("Can't delete thumbnail and preview of !" + str(instance.pk))

pre_delete.connect(file_cleanup, sender=Picture)

class PictureTranslation(MultilingualTranslation):
	class Meta:
		unique_together = ('parent', 'language_code')

	parent = models.ForeignKey(Picture, related_name='translations')
	name = models.CharField(verbose_name=_(u"Picture name"), max_length=100)

class LinkType(models.Model):
	type_tag = models.CharField(verbose_name=_(u"Link name"), max_length=25)
	date_pub = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.type_tag

	def __unicode__(self):
		return self.type_tag

class Link(models.Model):
	link_type = models.ForeignKey(LinkType)
	link_url = models.URLField(verbose_name=_(u"Link URL"), max_length=200)
	date_pub = models.DateTimeField(auto_now_add=True)
	@classmethod
	def create(cls, l_type):
		up = cls(link_type=l_type)
		# do something with the book
		return up

	def __str__(self):
		return self.link_type.type_tag

	def __unicode__(self):
		return self.link_type.type_tag

class UserProfile(models.Model):
	user = models.ForeignKey(User, unique=True)
	links = models.ManyToManyField(Link, blank=True)
	original_picture = models.CharField(verbose_name=_(u"original_url"), max_length=255, blank=True, default='')
	user_picture = models.CharField(verbose_name=_(u"photo_url"), max_length=255, blank=True, default='')
	user_thumbnail = models.CharField(verbose_name=_(u"thumbnail_url"), max_length=255, blank=True, default='')
	@classmethod
	def create(cls, user):
		up = cls(user=user)
		# do something with the book
		return up
	def get_thumb(self):
		if self.user_thumbnail:

care/templates/care/base.html
{% load care_extra %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>pics.Care</title>

    <!-- Bootstrap -->
    <link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/signin.css" rel="stylesheet">
    <link href="{{STATIC_URL}}font-awesome-4.2.0/css/font-awesome.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/ato.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/bootstrap-select.min.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/bootstrap-tagsinput.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/jquery.Jcrop.css" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{{STATIC_URL}}/img/favicon.ico"/>
    
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block headerscript %}{% endblock %}
  </head>
  <body>
{% block header %}
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">pics.Care</a>
        </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li  class="{% active_page request "detail" %} {% active_page request "edit" %}"><a href="{% url 'care:detail' %}"><i class="fa fa-image fa-lg"></i> {% trans "My pictures" %}</a></li>
                <li class="{% active_page request "myinfo" %}"><a href="{% url 'care:myinfo' %}"><i class="fa fa-user fa-lg"></i> {% trans "My info" %}</a></li>
                <li class="{% active_page request "upload" %}">
                    <a href="{% url 'care:upload' %}"><i class="fa fa-upload fa-lg"></i> {% trans "Upload" %}</a>
                </li>
                <li class="dropdown">
                  <a href="{% url 'ato:social' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-users fa-lg"></i> {% trans "Photos" %} <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'ato:social' %}{% active_lang request %}/popular"><i class="fa fa-image fa-lg"></i> {% trans "Photos" %}</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'ato:social' %}{% active_lang request %}/authors"><i class="fa fa-users fa-lg"></i> {% trans "Photographers" %}</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'ato:social' %}{% active_lang request %}/categories"><i class="fa fa-th fa-lg"></i> {% trans "Categories" %}</a></li>
                  </ul>
                </li>
            </ul>
          
            <ul class="nav navbar-nav navbar-right">

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{% trans "Language" %} <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                      {% for lang in LANGUAGES %}
                        
                          <form name="setLang{{ lang.1 }}" id="setLang{{ lang.1 }}" action="/i18n/setlang/" method="POST">
                            <li>
                            {% csrf_token %}
                            <input name="next" type="hidden" value="/care">
                            <input type="hidden" name="language" value="{{ lang.0 }}">
                            <a href="" class="{{ lang.1 }} form-li" onclick="document.getElementById('setLang{{ lang.1 }}').submit();return false;">{% if lang.1 == 'English' %} {% trans "English" %} {% else %} {% trans "Ukrainian" %} {% endif %}</a>
                            </li>
                          </form>
                        
                      {% endfor %}
                    </ul>
                  </li>
                    
                <li>
                    <a href="{% url 'care:myinfo' %}" class="user-a">
                      {% for profile in user.userprofile_set.all %}
                      <img src="{{profile.get_thumb}}" class="img img-thumbnail user-thumbnail" />
                      {% endfor %}
                      &nbsp;{{ user.get_username }}
                    </a>
                  </li>
                    
                <li><a href="{% url 'care:logout' %}" class="navbar-link"><i class="fa fa-sign-out fa-lg"></i> {% trans "Logout" %} </a></li>
                
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
{% endblock %}

<div class="container">
    {% block content %}{% endblock %}
</div>
<div class="footer">
    <div class="container">
        <!--{% for lang in LANGUAGES %}
            <div class="text-left t">
              <form name="setLang{{ lang.1}}" action="/i18n/setlang/" method="POST">
                {% csrf_token %}
                <input name="next" type="hidden" value="/care/detail">
                <input type="hidden" name="language" value="{{ lang.0 }}">
                <a href="#" onclick="document.setLang{{ lang.1 }}.submit();
                    return false;">Language</a>
              </form>
            </div>
          {% endfor %} -->
        <div class="text-center t">
          <p class="text-muted">intelliGT 2015 &copy;</p>
        </div>
    </div>    
</div>
    
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{{STATIC_URL}}js/bootstrap.min.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap.file-input.js"></script>
    <script type="text/javascript">
        $('input[type=file]').bootstrapFileInput();
        $('.file-inputs').bootstrapFileInput();
    </script>
    <script src="{{STATIC_URL}}js/bootstrap-select.min.js"></script>
    <script src="{{STATIC_URL}}js/jquery.color.js"></script>
    <script src="{{STATIC_URL}}js/jquery.Jcrop.js"></script>
    <script src="{{STATIC_URL}}js/jquery.cookie.js"></script>
<!--    <script type="text/javascript" src="/media/js/admin/RelatedObjectLookups.js"></script> -->
    <script src="{{STATIC_URL}}js/bootstrap3-typeahead.js"></script> 
    <script src="{{STATIC_URL}}js/bootstrap-tagsinput.js"></script>
    <script src="{{STATIC_URL}}js/jquery.transit.min.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-toolkit.js" ></script>
    
  </body>
</html>

care/templates/care/loggedout.html
{% extends 'care/base.html' %}
{% load i18n %}
{% block header %}
{% endblock %}
{% block content %}

<form class="form-signin text-center" method="post">
{% csrf_token %}

	<h2 class="form-signin-heading">{% trans "Logged out" %}</h2>
	<h4 class="form-signin-heading">{% trans "Thanks for spending some quality time with the ATO.care today." %}</h4>

	<a href="/care/login">{% trans "Log in again" %}</a>
</form>
<script src="{{STATIC_URL}}js/jquery.min.js"></script>

<script language="javascript" type="text/javascript">
     <!--
     window.setTimeout('window.location="/care/login"; ',2800);
     // -->
 </script>

{% endblock %}

care/templates/care/login.html
{% extends 'care/base.html' %}
{% load i18n %}
{% block header %}
{% endblock %}
{% block content %}
<br>
<div class="row">
    <div class="col-md-6 visible-md visible-lg">
    	<img src="{{STATIC_URL}}img/help-ua.jpg" alt="ATO.care" class="img-responsive img-rounded">
    </div>
    <div class="col-md-6">
    	<br />
    	<br />
    	<br />
		<form class="form-signin" method="post" action="{% url 'django.contrib.auth.views.login' %}">
		{% csrf_token %}

			{% if form.errors %}
			<p><i class="fa fa-info-circle fa-1x"></i>&nbsp;{% trans "Your username and password didn't match. Please try again." %}</p>
			{% endif %}

			<h2 class="form-signin-heading">{% trans "Please sign in" %}</h2>
				

			<input type="text" class="form-control" placeholder="Username" required="" autofocus="" maxlength="254" name="username">
			<input type="password" class="form-control" placeholder="Password" required="" name="password">
			<!--<label class="checkbox">
			  <input type="checkbox" value="remember-me"> Remember me
			</label>-->

			<button class="btn btn-lg btn-default btn-block" type="submit">{% trans "Sign in" %}</button>
			<input type="hidden" name="next" value="{{ next }}" />
			<div class="text-center">
				<h4>{% trans "or" %}</h4>
			</div>
			<button type="button" class="btn btn-primary btn-lg btn-block"
			onclick="go_to_url('/accounts/register/');">{% trans "Register" %}</button>
			

			<br>
			<div class="row">
				<div class="col-sm-6 col-xs-6 col-lg-6 col-md-6 text-left">
					<a href="{% url 'ato:index' %}"><i class="fa fa-arrow-left"></i>&nbsp;{% trans "Back to Home" %}</a>
				</div>
				<div class="col-sm-6 col-xs-6 col-lg-6 col-md-6 text-right">
					<a href="/reset/recover/">{% trans "Forgot you password?" %}</a>
				</div>
			</div>
		</form>
		

	</div>
</div>
<script src="{{STATIC_URL}}js/jquery.min.js"></script>

<script>
    function go_to_url(url) {
        window.location = url;
    }
</script>
{% endblock %}